"""Logique du jeu du Pendu : mots avec indices, difficulte, calcul du score."""

import random

# Chaque mot est associe a un indice ecrit a la main, affiche pendant la partie
# (visible par les innocents en mode Imposteur, par tous en mode Classique).
MOTS: dict[str, list[dict]] = {
    "informatique": [
        {"mot": "code", "indice": "Suite d'instructions qu'un programme execute."},
        {"mot": "java", "indice": "Langage de programmation tres utilise pour les applications d'entreprise."},
        {"mot": "unix", "indice": "Famille de systemes d'exploitation a l'origine de Linux."},
        {"mot": "wifi", "indice": "Technologie qui permet de se connecter a un reseau sans fil."},
        {"mot": "html", "indice": "Langage utilise pour structurer les pages web."},
        {"mot": "json", "indice": "Format leger utilise pour echanger des donnees structurees."},
        {"mot": "blog", "indice": "Site web ou l'on publie des articles regulierement."},
        {"mot": "carte", "indice": "Composant qu'on insere dans un ordinateur, comme une carte graphique."},
        {"mot": "ecran", "indice": "Ce qui affiche l'image de ton ordinateur."},
        {"mot": "cable", "indice": "Fil qui relie deux appareils entre eux."},
        {"mot": "linux", "indice": "Systeme d'exploitation libre, base de nombreuses distributions comme Debian."},
        {"mot": "forum", "indice": "Espace en ligne ou les utilisateurs discutent par messages."},
        {"mot": "texte", "indice": "Contenu ecrit stocke dans un fichier ou affiche a l'ecran."},
        {"mot": "image", "indice": "Fichier qui represente un visuel, comme une photo."},
        {"mot": "photo", "indice": "Image capturee par un appareil ou un telephone."},
        {"mot": "video", "indice": "Fichier qui combine des images animees et du son."},
        {"mot": "audio", "indice": "Fichier ou flux qui contient uniquement du son."},
        {"mot": "fibre", "indice": "Type de cable tres rapide utilise pour internet."},
        {"mot": "modem", "indice": "Appareil qui connecte un reseau local a internet."},
        {"mot": "souris", "indice": "Peripherique qu'on deplace avec la main pour cliquer."},
        {"mot": "disque", "indice": "Composant qui stocke les fichiers de maniere permanente."},
        {"mot": "reseau", "indice": "Ensemble d'appareils connectes entre eux."},
        {"mot": "python", "indice": "Langage de programmation nomme d'apres une troupe de comiques."},
        {"mot": "debian", "indice": "Une distribution Linux stable et populaire."},
        {"mot": "octet", "indice": "Unite d'information composee de huit bits."},
        {"mot": "pixel", "indice": "Plus petit point qui compose une image numerique."},
        {"mot": "bogue", "indice": "Erreur inattendue dans un programme."},
        {"mot": "robot", "indice": "Machine programmee pour executer des taches automatiquement."},
        {"mot": "cache", "indice": "Memoire rapide qui garde des donnees utilisees frequemment."},
        {"mot": "noyau", "indice": "Coeur d'un systeme d'exploitation qui gere le materiel."},
        {"mot": "paquet", "indice": "Petit bloc de donnees envoye sur un reseau."},
        {"mot": "widget", "indice": "Petit module d'interface qu'on ajoute a un ecran ou une page."},
        {"mot": "plugin", "indice": "Extension qu'on ajoute a un logiciel pour lui donner de nouvelles fonctions."},
        {"mot": "thread", "indice": "Fil d'execution qui tourne en parallele dans un programme."},
        {"mot": "erreur", "indice": "Message qui signale qu'un probleme est survenu dans le code."},
        {"mot": "backup", "indice": "Copie de securite de tes fichiers."},
        {"mot": "online", "indice": "Etat d'un appareil ou d'un service connecte a internet."},
        {"mot": "boucle", "indice": "Structure qui repete un bloc de code plusieurs fois."},
        {"mot": "objet", "indice": "En programmation, une instance qui regroupe donnees et actions."},
        {"mot": "classe", "indice": "Modele qui definit la structure d'un objet."},
        {"mot": "tampon", "indice": "Zone de memoire temporaire pour stocker des donnees en transit."},
        {"mot": "pilote", "indice": "Logiciel qui permet au systeme de communiquer avec un peripherique."},
        {"mot": "domaine", "indice": "Nom qui identifie un site sur internet, comme exemple.com."},
        {"mot": "adresse", "indice": "Identifiant unique qui localise un appareil sur un reseau."},
        {"mot": "session", "indice": "Periode pendant laquelle un utilisateur est connecte a un service."},
        {"mot": "message", "indice": "Information envoyee d'un utilisateur ou systeme a un autre."},
        {"mot": "matrice", "indice": "Tableau de nombres organise en lignes et en colonnes."},
        {"mot": "vecteur", "indice": "Structure qui contient une liste ordonnee de valeurs."},
        {"mot": "clavier", "indice": "Peripherique avec des touches pour taper du texte."},
        {"mot": "serveur", "indice": "Ordinateur qui repond aux demandes d'autres machines."},
        {"mot": "fichier", "indice": "Unite de donnees enregistree sur un disque."},
        {"mot": "systeme", "indice": "Ensemble de logiciels qui gere un ordinateur (Windows, Linux...)."},
        {"mot": "identite", "indice": "Ensemble des informations qui permettent de reconnaitre un utilisateur."},
        {"mot": "cryptage", "indice": "Autre mot pour designer le chiffrement des donnees."},
        {"mot": "scalaire", "indice": "Valeur simple, unique, par opposition a un tableau ou une matrice."},
        {"mot": "heritage", "indice": "Mecanisme qui permet a une classe de reprendre les proprietes d'une autre."},
        {"mot": "logiciel", "indice": "Programme installe sur un appareil."},
        {"mot": "internet", "indice": "Reseau mondial qui relie des millions d'ordinateurs."},
        {"mot": "variable", "indice": "En programmation, un espace qui stocke une valeur."},
        {"mot": "fonction", "indice": "Bloc de code reutilisable qui accomplit une tache precise."},
        {"mot": "programme", "indice": "Sequence d'instructions ecrite pour un ordinateur."},
        {"mot": "connexion", "indice": "Lien etabli entre deux appareils ou services."},
        {"mot": "operateur", "indice": "Symbole qui effectue une operation, comme + ou -."},
        {"mot": "iterateur", "indice": "Objet qui permet de parcourir les elements d'une collection un par un."},
        {"mot": "recursion", "indice": "Technique ou une fonction s'appelle elle-meme."},
        {"mot": "execution", "indice": "Moment ou un programme tourne reellement sur la machine."},
        {"mot": "librairie", "indice": "Ensemble de code reutilisable qu'on importe dans un projet."},
        {"mot": "framework", "indice": "Structure de base qui guide la construction d'une application."},
        {"mot": "pointeur", "indice": "Variable qui contient l'adresse memoire d'une autre variable."},
        {"mot": "routeur", "indice": "Appareil qui dirige le trafic entre plusieurs reseaux."},
        {"mot": "interface", "indice": "Point de contact entre un utilisateur et un systeme."},
        {"mot": "processus", "indice": "Programme en cours d'execution sur un ordinateur."},
        {"mot": "memoire", "indice": "Composant qui stocke temporairement les donnees utilisees par le systeme."},
        {"mot": "extension", "indice": "Petit module qui ajoute des fonctionnalites a un logiciel."},
        {"mot": "attribut", "indice": "Caracteristique associee a un objet en programmation."},
        {"mot": "constante", "indice": "Valeur qui ne change jamais pendant l'execution d'un programme."},
        {"mot": "parametre", "indice": "Valeur transmise a une fonction pour qu'elle l'utilise."},
        {"mot": "diagramme", "indice": "Representation visuelle d'un systeme ou d'un processus."},
        {"mot": "structure", "indice": "Maniere dont les elements d'un programme sont organises."},
        {"mot": "smartphone", "indice": "Telephone intelligent capable d'executer des applications."},
        {"mot": "processeur", "indice": "Composant qui execute les calculs au coeur d'un ordinateur."},
        {"mot": "utilitaire", "indice": "Petit programme concu pour une tache precise et simple."},
        {"mot": "compilation", "indice": "Etape qui transforme le code source en programme executable."},
        {"mot": "simulation", "indice": "Reproduction informatique du comportement d'un systeme reel."},
        {"mot": "middleware", "indice": "Logiciel intermediaire qui relie deux applications entre elles."},
        {"mot": "ordinateur", "indice": "Machine qui traite l'information, sur ton bureau ou tes genoux."},
        {"mot": "compilateur", "indice": "Outil qui transforme du code source en programme executable."},
        {"mot": "algorithme", "indice": "Suite d'etapes logiques pour resoudre un probleme."},
        {"mot": "application", "indice": "Programme concu pour un usage precis, souvent sur mobile."},
        {"mot": "imprimante", "indice": "Peripherique qui transfere un document numerique sur papier."},
        {"mot": "passerelle", "indice": "Point de connexion entre deux reseaux differents."},
        {"mot": "compression", "indice": "Technique qui reduit la taille d'un fichier."},
        {"mot": "encapsulation", "indice": "Principe qui cache les details internes d'un objet."},
        {"mot": "polymorphisme", "indice": "Capacite d'un objet a prendre plusieurs formes selon le contexte."},
        {"mot": "telechargement", "indice": "Action de recuperer un fichier depuis un serveur distant."},
        {"mot": "configuration", "indice": "Ensemble des reglages qui definissent le comportement d'un systeme."},
        {"mot": "virtualisation", "indice": "Technique qui simule plusieurs systemes sur une seule machine physique."},
        {"mot": "microprocesseur", "indice": "Circuit qui execute les instructions au coeur d'un ordinateur."},
    ],
    "cybersecurite": [
        {"mot": "scan", "indice": "Action de fouiller un reseau a la recherche de ports ouverts."},
        {"mot": "port", "indice": "Point d'entree numerote qu'un service reseau utilise."},
        {"mot": "spam", "indice": "Message indesirable envoye en masse, souvent publicitaire."},
        {"mot": "root", "indice": "Compte disposant de tous les droits sur un systeme Linux."},
        {"mot": "virus", "indice": "Programme malveillant qui se propage en s'attachant a d'autres fichiers."},
        {"mot": "audit", "indice": "Examen approfondi de la securite d'un systeme."},
        {"mot": "acces", "indice": "Droit d'utiliser une ressource ou un systeme."},
        {"mot": "admin", "indice": "Personne qui gere et configure un systeme ou un reseau."},
        {"mot": "login", "indice": "Action de se connecter a un compte avec ses identifiants."},
        {"mot": "cyber", "indice": "Prefixe qui designe tout ce qui touche au numerique et a la securite."},
        {"mot": "proxy", "indice": "Serveur intermediaire qui relaie les requetes reseau."},
        {"mot": "risque", "indice": "Probabilite qu'une menace exploite une faiblesse."},
        {"mot": "faille", "indice": "Faiblesse exploitable dans un systeme ou un logiciel."},
        {"mot": "hacker", "indice": "Personne qui explore ou exploite des systemes informatiques."},
        {"mot": "donnee", "indice": "Information brute traitee ou stockee par un systeme."},
        {"mot": "secret", "indice": "Information qui doit rester connue seulement de quelques personnes."},
        {"mot": "espion", "indice": "Logiciel ou personne qui surveille discretement une activite."},
        {"mot": "fraude", "indice": "Action malhonnete visant a tromper un systeme ou une personne."},
        {"mot": "botnet", "indice": "Reseau d'appareils infectes controles a distance par un attaquant."},
        {"mot": "troyen", "indice": "Programme qui se cache dans un logiciel en apparence normal."},
        {"mot": "cookie", "indice": "Petit fichier stocke par un site pour se souvenir du visiteur."},
        {"mot": "pirate", "indice": "Personne qui s'introduit illegalement dans un systeme."},
        {"mot": "voleur", "indice": "Celui qui derobe des donnees ou des identifiants."},
        {"mot": "cible", "indice": "Systeme ou personne visee par une attaque."},
        {"mot": "leurre", "indice": "Faux systeme cree pour attirer un attaquant."},
        {"mot": "trace", "indice": "Empreinte laissee par une activite sur un systeme."},
        {"mot": "alerte", "indice": "Signal declenche quand une activite suspecte est detectee."},
        {"mot": "verrou", "indice": "Mecanisme qui empeche un acces non autorise."},
        {"mot": "jeton", "indice": "Element qui prouve temporairement une identite ou une session."},
        {"mot": "preuve", "indice": "Element qui demontre qu'un incident a eu lieu."},
        {"mot": "patch", "indice": "Correctif applique pour reparer une faille."},
        {"mot": "rootkit", "indice": "Ensemble d'outils qui cache la presence d'un attaquant sur un systeme."},
        {"mot": "keylogger", "indice": "Logiciel qui enregistre secretement les touches tapees au clavier."},
        {"mot": "honeypot", "indice": "Systeme piege concu pour attirer et etudier les attaquants."},
        {"mot": "maliciel", "indice": "Mot francais officiel pour designer un logiciel malveillant."},
        {"mot": "politique", "indice": "Ensemble de regles de securite qu'une organisation doit suivre."},
        {"mot": "renifleur", "indice": "Outil qui capture et analyse le trafic circulant sur un reseau."},
        {"mot": "chiffre", "indice": "Resultat d'un texte transforme par un algorithme de chiffrement."},
        {"mot": "anomalie", "indice": "Comportement inhabituel qui peut signaler une attaque."},
        {"mot": "reponse", "indice": "Ensemble des actions prises apres la detection d'un incident."},
        {"mot": "detection", "indice": "Processus qui identifie une menace ou une activite suspecte."},
        {"mot": "isolation", "indice": "Action de separer un systeme infecte du reste du reseau."},
        {"mot": "correctif", "indice": "Mise a jour qui corrige une faille de securite."},
        {"mot": "pentest", "indice": "Test d'intrusion autorise pour trouver des failles."},
        {"mot": "malware", "indice": "Terme general pour un logiciel malveillant."},
        {"mot": "attaque", "indice": "Tentative de compromettre un systeme."},
        {"mot": "defense", "indice": "Ensemble des mesures qui protegent un systeme."},
        {"mot": "firewall", "indice": "Dispositif qui filtre le trafic reseau entrant et sortant."},
        {"mot": "phishing", "indice": "Technique qui pousse une victime a reveler ses identifiants."},
        {"mot": "spoofing", "indice": "Technique qui usurpe une identite ou une adresse reseau."},
        {"mot": "protocole", "indice": "Ensemble de regles qui definissent une communication reseau."},
        {"mot": "exploit", "indice": "Code qui tire parti d'une vulnerabilite precise."},
        {"mot": "backdoor", "indice": "Acces cache laisse volontairement dans un systeme."},
        {"mot": "intrusion", "indice": "Acces non autorise a un systeme."},
        {"mot": "incident", "indice": "Evenement de securite qui necessite une reponse."},
        {"mot": "empreinte", "indice": "Signature unique qui identifie un fichier ou un appareil."},
        {"mot": "signature", "indice": "Motif connu qui permet de reconnaitre une menace."},
        {"mot": "biometrie", "indice": "Authentification basee sur une caracteristique physique unique."},
        {"mot": "espionnage", "indice": "Collecte secrete d'informations sensibles sur une cible."},
        {"mot": "conformite", "indice": "Respect des lois et normes de securite en vigueur."},
        {"mot": "gouvernance", "indice": "Ensemble des regles qui encadrent la gestion de la securite."},
        {"mot": "resilience", "indice": "Capacite d'un systeme a continuer de fonctionner malgre une attaque."},
        {"mot": "protection", "indice": "Ensemble des mesures qui defendent un systeme contre les menaces."},
        {"mot": "quarantaine", "indice": "Zone isolee ou l'on place un fichier suspect avant analyse."},
        {"mot": "obfuscation", "indice": "Technique qui rend un code difficile a comprendre pour le cacher."},
        {"mot": "exfiltration", "indice": "Extraction non autorisee de donnees hors d'un systeme."},
        {"mot": "remediation", "indice": "Ensemble des actions pour corriger un incident de securite."},
        {"mot": "cloisonnement", "indice": "Separation stricte entre differentes zones d'un systeme."},
        {"mot": "sensibilisation", "indice": "Formation qui apprend aux utilisateurs a reconnaitre les menaces."},
        {"mot": "ransomware", "indice": "Logiciel qui chiffre les fichiers et exige une rancon."},
        {"mot": "chiffrement", "indice": "Procede qui rend des donnees illisibles sans une cle."},
        {"mot": "cryptographie", "indice": "Science qui etudie comment proteger l'information par le calcul."},
        {"mot": "vulnerabilite", "indice": "Faiblesse precise, documentee, qu'un attaquant peut exploiter."},
        {"mot": "certificat", "indice": "Document numerique qui prouve l'identite d'un site ou d'un service."},
        {"mot": "sauvegarde", "indice": "Copie des donnees conservee pour les restaurer en cas de probleme."},
        {"mot": "hameconnage", "indice": "Terme francais pour designer le phishing."},
        {"mot": "usurpation", "indice": "Fait de se faire passer pour quelqu'un d'autre."},
        {"mot": "segmentation", "indice": "Division d'un reseau en zones isolees pour limiter les risques."},
        {"mot": "steganographie", "indice": "Technique qui cache un message a l'interieur d'un autre fichier."},
        {"mot": "authentification", "indice": "Processus qui verifie qu'un utilisateur est bien qui il pretend etre."},
    ],
    "animaux": [
        {"mot": "chat", "indice": "Animal domestique qui ronronne et griffe le canape."},
        {"mot": "lion", "indice": "Grand felin surnomme le roi des animaux."},
        {"mot": "loup", "indice": "Canide sauvage qui vit et chasse en meute."},
        {"mot": "ours", "indice": "Gros mammifere qui hiberne en hiver."},
        {"mot": "puma", "indice": "Grand felin d'Amerique aussi appele couguar."},
        {"mot": "lynx", "indice": "Felin sauvage aux oreilles pointues surmontees de pinceaux de poils."},
        {"mot": "porc", "indice": "Animal de ferme eleve pour sa viande, cousin du sanglier."},
        {"mot": "cane", "indice": "Femelle du canard."},
        {"mot": "lama", "indice": "Mammifere andin cousin du chameau, sans bosse."},
        {"mot": "zebu", "indice": "Bovin a bosse eleve surtout en Asie et en Afrique."},
        {"mot": "raie", "indice": "Poisson plat au corps en forme de losange."},
        {"mot": "thon", "indice": "Gros poisson tres peche, souvent en boite."},
        {"mot": "sole", "indice": "Poisson plat prise pour sa chair fine."},
        {"mot": "crabe", "indice": "Crustace qui marche de cote."},
        {"mot": "guepe", "indice": "Insecte jaune et noir au dard douloureux."},
        {"mot": "chien", "indice": "Le meilleur ami de l'humain, il aboie."},
        {"mot": "singe", "indice": "Primate agile qui grimpe aux arbres."},
        {"mot": "tigre", "indice": "Grand felin raye, orange et noir."},
        {"mot": "zebre", "indice": "Equide africain couvert de rayures noires et blanches."},
        {"mot": "aigle", "indice": "Rapace majestueux symbole de force dans plusieurs pays."},
        {"mot": "hibou", "indice": "Oiseau nocturne aux aigrettes bien visibles sur la tete."},
        {"mot": "vache", "indice": "Bovin domestique eleve pour son lait."},
        {"mot": "mulet", "indice": "Croisement entre un ane et une jument, tres resistant."},
        {"mot": "poule", "indice": "Oiseau de basse-cour qui pond des oeufs."},
        {"mot": "dinde", "indice": "Grand oiseau de ferme souvent servi lors des fetes."},
        {"mot": "phoque", "indice": "Mammifere marin qui se deplace en rampant sur la banquise."},
        {"mot": "morse", "indice": "Grand mammifere marin arctique reconnaissable a ses defenses."},
        {"mot": "merle", "indice": "Oiseau noir au chant melodieux, courant dans les jardins."},
        {"mot": "cygne", "indice": "Grand oiseau aquatique blanc au long cou elegant."},
        {"mot": "heron", "indice": "Grand oiseau echassier qui peche au bord de l'eau."},
        {"mot": "moule", "indice": "Petit mollusque bivalve qu'on cuisine souvent avec des frites."},
        {"mot": "otarie", "indice": "Mammifere marin qui applaudit avec ses nageoires dans les spectacles."},
        {"mot": "iguane", "indice": "Reptile vert souvent garde comme animal de compagnie."},
        {"mot": "lievre", "indice": "Cousin du lapin, plus rapide et plus grand."},
        {"mot": "renard", "indice": "Canide rusé a la queue touffue."},
        {"mot": "tortue", "indice": "Reptile lent protege par une carapace."},
        {"mot": "chacal", "indice": "Canide africain souvent associe aux charognards."},
        {"mot": "buffle", "indice": "Gros bovide sauvage aux cornes impressionnantes."},
        {"mot": "mygale", "indice": "Grosse araignee poilue qui impressionne beaucoup de monde."},
        {"mot": "faucon", "indice": "Rapace rapide utilise autrefois pour la chasse."},
        {"mot": "caille", "indice": "Petit oiseau de la meme famille que la perdrix."},
        {"mot": "faisan", "indice": "Oiseau au plumage colore souvent chasse en campagne."},
        {"mot": "requin", "indice": "Grand poisson predateur craint des baigneurs."},
        {"mot": "murene", "indice": "Poisson serpentiforme qui se cache dans les rochers."},
        {"mot": "truite", "indice": "Poisson d'eau douce tres peche, cousin du saumon."},
        {"mot": "saumon", "indice": "Poisson qui remonte les rivieres pour se reproduire."},
        {"mot": "pigeon", "indice": "Oiseau urbain tres commun, parfois appele rat des villes."},
        {"mot": "toucan", "indice": "Oiseau tropical reconnaissable a son enorme bec colore."},
        {"mot": "poulpe", "indice": "Mollusque a huit tentacules tres intelligent."},
        {"mot": "calmar", "indice": "Mollusque marin proche de la seiche, aux dix tentacules."},
        {"mot": "meduse", "indice": "Animal marin gelatineux dont la piqure peut bruler."},
        {"mot": "homard", "indice": "Crustace a grosses pinces tres prise en gastronomie."},
        {"mot": "huitre", "indice": "Mollusque bivalve consomme cru, parfois source de perles."},
        {"mot": "limace", "indice": "Mollusque terrestre sans coquille, cousin de l'escargot."},
        {"mot": "cafard", "indice": "Insecte resistant souvent associe a la salete."},
        {"mot": "cigale", "indice": "Insecte qui chante fort l'ete en frottant ses ailes."},
        {"mot": "frelon", "indice": "Grosse guepe dont la piqure est tres douloureuse."},
        {"mot": "dauphin", "indice": "Mammifere marin tres intelligent qui communique par sifflements."},
        {"mot": "baleine", "indice": "Le plus grand mammifere marin de la planete."},
        {"mot": "gorille", "indice": "Grand primate puissant qui vit en Afrique."},
        {"mot": "sanglier", "indice": "Cousin sauvage du cochon, avec des defenses."},
        {"mot": "ecureuil", "indice": "Petit rongeur agile qui grimpe aux arbres et cache des noisettes."},
        {"mot": "moustique", "indice": "Petit insecte piqueur qui bourdonne la nuit."},
        {"mot": "scorpion", "indice": "Arachnide au dard venimeux au bout de la queue."},
        {"mot": "vautour", "indice": "Rapace charognard qui plane a la recherche de cadavres."},
        {"mot": "panthere", "indice": "Grand felin tachete, parfois totalement noir."},
        {"mot": "mangouste", "indice": "Petit mammifere connu pour affronter les serpents."},
        {"mot": "tarentule", "indice": "Grosse araignee au nom impressionnant mais souvent peu dangereuse."},
        {"mot": "chimpanze", "indice": "Primate tres proche genetiquement de l'humain."},
        {"mot": "perdrix", "indice": "Petit oiseau de plaine souvent chasse."},
        {"mot": "anguille", "indice": "Poisson long et glissant qui migre jusqu'en mer des Sargasses."},
        {"mot": "corbeau", "indice": "Grand oiseau noir intelligent au croassement caracteristique."},
        {"mot": "moineau", "indice": "Petit oiseau brun tres commun dans les villes."},
        {"mot": "cigogne", "indice": "Grand oiseau migrateur qui niche sur les toits et les cheminees."},
        {"mot": "pelican", "indice": "Oiseau au grand bec muni d'une poche pour pecher."},
        {"mot": "perroquet", "indice": "Oiseau colore capable d'imiter la parole humaine."},
        {"mot": "colibri", "indice": "Minuscule oiseau capable de voler sur place en battant tres vite des ailes."},
        {"mot": "sardine", "indice": "Petit poisson souvent vendu en boite a l'huile."},
        {"mot": "maquereau", "indice": "Poisson bleu tres peche dans l'Atlantique."},
        {"mot": "langouste", "indice": "Crustace marin sans pinces, cousin du homard."},
        {"mot": "crevette", "indice": "Petit crustace tres consomme, rose une fois cuit."},
        {"mot": "lombric", "indice": "Ver de terre qui ameliore la qualite du sol."},
        {"mot": "libellule", "indice": "Insecte aux ailes transparentes qui vole pres de l'eau."},
        {"mot": "bourdon", "indice": "Gros insecte poilu de la famille des abeilles."},
        {"mot": "caracal", "indice": "Felin sauvage africain aux oreilles pointues et touffues."},
        {"mot": "elephant", "indice": "Plus grand mammifere terrestre, reconnaissable a sa trompe."},
        {"mot": "pingouin", "indice": "Oiseau des regions froides qui ne vole pas."},
        {"mot": "cameleon", "indice": "Reptile capable de changer de couleur."},
        {"mot": "papillon", "indice": "Insecte aux ailes colorees, issu d'une chenille."},
        {"mot": "escargot", "indice": "Mollusque terrestre a coquille, plat traditionnel francais."},
        {"mot": "crocodile", "indice": "Reptile aquatique aux machoires puissantes."},
        {"mot": "kangourou", "indice": "Marsupial australien qui se deplace par bonds."},
        {"mot": "dromadaire", "indice": "Mammifere du desert avec une seule bosse."},
        {"mot": "coccinelle", "indice": "Petit insecte rouge a pois noirs porte-bonheur."},
        {"mot": "sauterelle", "indice": "Insecte sauteur aux longues pattes arriere."},
        {"mot": "hirondelle", "indice": "Oiseau migrateur au vol rapide, annonciateur du printemps."},
        {"mot": "grenouille", "indice": "Amphibien sauteur qui coasse pres des mares."},
        {"mot": "rhinoceros", "indice": "Gros mammifere a une ou deux cornes sur le museau."},
        {"mot": "hippopotame", "indice": "Enorme mammifere semi-aquatique d'Afrique, plus dangereux qu'il n'y parait."},
        {"mot": "salamandre", "indice": "Petit amphibien souvent noir tachete de jaune."},
        {"mot": "ornithorynque", "indice": "Mammifere australien etrange qui pond des oeufs et a un bec de canard."},
        {"mot": "hippocampe", "indice": "Petit poisson qui nage la tete droite, le male porte les oeufs."},
        {"mot": "chinchilla", "indice": "Petit rongeur sud-americain au pelage tres dense et doux."},
        {"mot": "rhinolophe", "indice": "Chauve-souris aux plis nasaux en forme de fer a cheval."},
        {"mot": "phacochere", "indice": "Cousin sauvage du sanglier vivant en Afrique, avec de grosses defenses."},
        {"mot": "polatouche", "indice": "Petit rongeur capable de planer grace a une membrane entre ses pattes."},
        {"mot": "pachyderme", "indice": "Terme general pour les gros mammiferes a peau tres epaisse, comme l'elephant."},
    ],
    "geographie": [
        {"mot": "iran", "indice": "Pays du Moyen-Orient, ancienne Perse."},
        {"mot": "irak", "indice": "Pays du Moyen-Orient traverse par le Tigre et l'Euphrate."},
        {"mot": "oman", "indice": "Pays du Moyen-Orient a la pointe de la peninsule arabique."},
        {"mot": "inde", "indice": "Pays d'Asie du Sud tres peuple, berceau du Gange."},
        {"mot": "cuba", "indice": "Ile des Caraibes connue pour ses vieilles voitures americaines."},
        {"mot": "asie", "indice": "Plus grand et plus peuple des continents."},
        {"mot": "baie", "indice": "Echancrure de la cote ou la mer s'avance dans les terres."},
        {"mot": "yemen", "indice": "Pays au sud de la peninsule arabique."},
        {"mot": "syrie", "indice": "Pays du Moyen-Orient voisin du Liban et de la Turquie."},
        {"mot": "corse", "indice": "Ile francaise de Mediterranee, surnommee l'ile de Beaute."},
        {"mot": "crete", "indice": "Plus grande ile de Grece."},
        {"mot": "malte", "indice": "Petit archipel europeen au sud de la Sicile."},
        {"mot": "suede", "indice": "Pays scandinave connu pour ses forets et ses lacs."},
        {"mot": "chine", "indice": "Pays le plus peuple du monde pendant longtemps, en Asie de l'Est."},
        {"mot": "japon", "indice": "Archipel d'Asie surnomme le pays du Soleil-Levant."},
        {"mot": "perou", "indice": "Pays d'Amerique du Sud ou se trouve le Machu Picchu."},
        {"mot": "chili", "indice": "Long pays tres etroit d'Amerique du Sud."},
        {"mot": "haiti", "indice": "Pays des Caraibes qui partage une ile avec la Republique dominicaine."},
        {"mot": "congo", "indice": "Pays d'Afrique traverse par un immense fleuve du meme nom."},
        {"mot": "kenya", "indice": "Pays d'Afrique de l'Est connu pour ses safaris."},
        {"mot": "ghana", "indice": "Pays d'Afrique de l'Ouest, ancien Cote-de-l'Or."},
        {"mot": "maroc", "indice": "Pays d'Afrique du Nord connu pour ses souks et le desert."},
        {"mot": "suisse", "indice": "Pays alpin europeen reconnu pour sa neutralite et ses montres."},
        {"mot": "canada", "indice": "Deuxieme plus grand pays du monde, au nord des Etats-Unis."},
        {"mot": "russie", "indice": "Plus grand pays du monde, a cheval sur l'Europe et l'Asie."},
        {"mot": "grece", "indice": "Pays mediterraneen berceau de la democratie."},
        {"mot": "coree", "indice": "Peninsule d'Asie divisee en deux pays."},
        {"mot": "taiwan", "indice": "Ile d'Asie de l'Est au large de la Chine."},
        {"mot": "israel", "indice": "Pays du Moyen-Orient au bord de la Mediterranee."},
        {"mot": "qatar", "indice": "Petit pays riche en petrole sur la peninsule arabique."},
        {"mot": "europe", "indice": "Continent qui comprend la France, l'Allemagne et l'Italie."},
        {"mot": "desert", "indice": "Vaste etendue aride ou il pleut tres peu."},
        {"mot": "vallee", "indice": "Depression allongee entre deux montagnes, souvent creusee par une riviere."},
        {"mot": "foret", "indice": "Vaste etendue couverte d'arbres."},
        {"mot": "golfe", "indice": "Grande baie bordee par les terres sur plusieurs cotes."},
        {"mot": "oasis", "indice": "Point d'eau et de vegetation au milieu du desert."},
        {"mot": "savane", "indice": "Grande plaine herbeuse tropicale, typique de l'Afrique."},
        {"mot": "isthme", "indice": "Bande de terre etroite qui relie deux masses continentales."},
        {"mot": "plaine", "indice": "Vaste etendue de terrain plat de faible altitude."},
        {"mot": "italie", "indice": "Pays en forme de botte, celebre pour ses pates."},
        {"mot": "egypte", "indice": "Pays d'Afrique du Nord celebre pour ses pyramides."},
        {"mot": "bresil", "indice": "Plus grand pays d'Amerique du Sud, celebre pour le carnaval."},
        {"mot": "volcan", "indice": "Montagne qui peut cracher de la lave."},
        {"mot": "fleuve", "indice": "Grand cours d'eau qui se jette dans la mer."},
        {"mot": "vietnam", "indice": "Pays d'Asie du Sud-Est en forme de S."},
        {"mot": "norvege", "indice": "Pays scandinave celebre pour ses fjords."},
        {"mot": "turquie", "indice": "Pays a cheval entre l'Europe et l'Asie."},
        {"mot": "pologne", "indice": "Pays d'Europe centrale voisin de l'Allemagne."},
        {"mot": "islande", "indice": "Ile nordique connue pour ses volcans et ses geysers."},
        {"mot": "jordanie", "indice": "Pays du Moyen-Orient ou se trouve la cite de Petra."},
        {"mot": "oceanie", "indice": "Continent qui comprend l'Australie et de nombreuses iles du Pacifique."},
        {"mot": "afrique", "indice": "Continent d'origine de l'humanite, riche en biodiversite."},
        {"mot": "colline", "indice": "Petite elevation de terrain, moins haute qu'une montagne."},
        {"mot": "riviere", "indice": "Cours d'eau qui se jette dans un autre cours d'eau."},
        {"mot": "detroit", "indice": "Bras de mer etroit qui separe deux terres."},
        {"mot": "cambodge", "indice": "Pays d'Asie du Sud-Est ou se trouve Angkor."},
        {"mot": "pakistan", "indice": "Pays d'Asie du Sud voisin de l'Inde."},
        {"mot": "ethiopie", "indice": "Pays d'Afrique de l'Est jamais colonise, berceau du cafe."},
        {"mot": "nigeria", "indice": "Pays le plus peuple d'Afrique."},
        {"mot": "algerie", "indice": "Plus grand pays d'Afrique par sa superficie."},
        {"mot": "cameroun", "indice": "Pays d'Afrique centrale surnomme l'Afrique en miniature."},
        {"mot": "senegal", "indice": "Pays d'Afrique de l'Ouest, ancienne colonie francaise."},
        {"mot": "toundra", "indice": "Vaste plaine froide sans arbres des regions polaires."},
        {"mot": "glacier", "indice": "Immense masse de glace qui se deplace lentement."},
        {"mot": "estuaire", "indice": "Embouchure elargie d'un fleuve qui se jette dans la mer."},
        {"mot": "littoral", "indice": "Zone de terre situee le long de la cote."},
        {"mot": "venezuela", "indice": "Pays d'Amerique du Sud riche en petrole, au bord des Caraibes."},
        {"mot": "guatemala", "indice": "Pays d'Amerique centrale ou vivaient les Mayas."},
        {"mot": "nicaragua", "indice": "Pays d'Amerique centrale connu pour ses volcans et ses lacs."},
        {"mot": "montagnes", "indice": "Reliefs eleves, comme les Alpes ou les Andes."},
        {"mot": "belgique", "indice": "Petit pays europeen celebre pour ses gaufres et son chocolat."},
        {"mot": "portugal", "indice": "Pays d'Europe au bord de l'Atlantique, voisin de l'Espagne."},
        {"mot": "colombie", "indice": "Pays d'Amerique du Sud connu pour son cafe."},
        {"mot": "tanzanie", "indice": "Pays d'Afrique de l'Est ou se trouve le Kilimandjaro."},
        {"mot": "tunisie", "indice": "Pays d'Afrique du Nord au bord de la Mediterranee."},
        {"mot": "roumanie", "indice": "Pays d'Europe de l'Est associe a la legende de Dracula."},
        {"mot": "finlande", "indice": "Pays scandinave surnomme le pays des mille lacs."},
        {"mot": "autriche", "indice": "Pays alpin europeen dont la capitale est Vienne."},
        {"mot": "thailande", "indice": "Pays d'Asie du Sud-Est surnomme le pays du sourire."},
        {"mot": "argentine", "indice": "Pays d'Amerique du Sud celebre pour le tango et le boeuf."},
        {"mot": "indonesie", "indice": "Pays d'Asie compose de milliers d'iles."},
        {"mot": "continent", "indice": "Vaste etendue de terre comme l'Afrique ou l'Asie."},
        {"mot": "frontiere", "indice": "Ligne qui separe deux pays."},
        {"mot": "peninsule", "indice": "Bande de terre entouree d'eau sur trois cotes."},
        {"mot": "plateau", "indice": "Etendue de terrain plat en altitude."},
        {"mot": "archipel", "indice": "Groupe d'iles proches les unes des autres."},
        {"mot": "equateur", "indice": "Ligne imaginaire qui divise la Terre en deux hemispheres."},
        {"mot": "meridien", "indice": "Ligne imaginaire qui relie le pole Nord au pole Sud."},
        {"mot": "himalaya", "indice": "Chaine de montagnes la plus haute du monde."},
        {"mot": "everest", "indice": "Plus haut sommet du monde, dans l'Himalaya."},
        {"mot": "madagascar", "indice": "Grande ile d'Afrique connue pour ses lemuriens."},
        {"mot": "afghanistan", "indice": "Pays montagneux d'Asie centrale."},
        {"mot": "kazakhstan", "indice": "Plus grand pays d'Asie centrale sans acces a la mer libre."},
        {"mot": "mozambique", "indice": "Pays d'Afrique australe au bord de l'ocean Indien."},
        {"mot": "hemisphere", "indice": "Moitie de la Terre, nord ou sud."},
        {"mot": "antarctique", "indice": "Continent glace situe au pole Sud."},
        {"mot": "mediterranee", "indice": "Mer entouree par l'Europe, l'Afrique et l'Asie."},
        {"mot": "philippines", "indice": "Archipel d'Asie du Sud-Est compose de plus de 7000 iles."},
        {"mot": "azerbaidjan", "indice": "Pays du Caucase au bord de la mer Caspienne."},
        {"mot": "ouzbekistan", "indice": "Pays d'Asie centrale traverse par l'ancienne route de la soie."},
        {"mot": "bangladesh", "indice": "Pays d'Asie du Sud tres peuple, traverse par de grands fleuves."},
        {"mot": "cordillere", "indice": "Longue chaine de montagnes, comme celle des Andes."},
        {"mot": "atmosphere", "indice": "Couche de gaz qui entoure une planete."},
        {"mot": "stratosphere", "indice": "Couche de l'atmosphere situee au-dessus de la troposphere."},
        {"mot": "biodiversite", "indice": "Variete des especes vivantes dans un milieu donne."},
        {"mot": "urbanisation", "indice": "Processus de croissance des villes et de leur population."},
    ],
    "sports": [
        {"mot": "judo", "indice": "Art martial japonais base sur les projections et les immobilisations."},
        {"mot": "golf", "indice": "Sport ou il faut envoyer une petite balle dans un trou avec un club."},
        {"mot": "boxe", "indice": "Sport de combat ou l'on frappe uniquement avec les poings."},
        {"mot": "velo", "indice": "Sport pratique sur deux roues, propulse par les jambes."},
        {"mot": "surf", "indice": "Sport ou l'on glisse sur les vagues avec une planche."},
        {"mot": "voile", "indice": "Sport nautique propulse par le vent grace a une toile."},
        {"mot": "danse", "indice": "Discipline artistique et sportive rythmee par la musique."},
        {"mot": "canoe", "indice": "Petite embarcation propulsee a la pagaie simple."},
        {"mot": "kayak", "indice": "Petite embarcation etroite propulsee avec une pagaie double."},
        {"mot": "cross", "indice": "Course a pied disputee en pleine nature, souvent avec des obstacles naturels."},
        {"mot": "sprint", "indice": "Course a pied tres courte et tres rapide."},
        {"mot": "relais", "indice": "Course d'equipe ou chaque coureur parcourt une portion avant de passer le temoin."},
        {"mot": "slalom", "indice": "Descente a ski entre une serie de portes a eviter en zigzag."},
        {"mot": "combat", "indice": "Affrontement direct entre deux adversaires, comme en boxe ou en lutte."},
        {"mot": "lutte", "indice": "Sport de combat au corps a corps sans coups portes."},
        {"mot": "saut", "indice": "Discipline qui consiste a franchir une hauteur ou une longueur."},
        {"mot": "lancer", "indice": "Discipline d'athletisme ou l'on projette un objet le plus loin possible."},
        {"mot": "peche", "indice": "Activite qui consiste a capturer des poissons."},
        {"mot": "chasse", "indice": "Activite qui consiste a traquer et capturer du gibier."},
        {"mot": "luge", "indice": "Sport de glisse sur neige ou glace, allonge sur un petit traineau."},
        {"mot": "paddle", "indice": "Sport nautique ou l'on se tient debout sur une planche en pagayant."},
        {"mot": "podium", "indice": "Estrade ou montent les trois premiers d'une competition."},
        {"mot": "record", "indice": "Meilleure performance jamais realisee dans une discipline."},
        {"mot": "equipe", "indice": "Groupe de joueurs qui s'affrontent ensemble contre un autre groupe."},
        {"mot": "rugby", "indice": "Sport collectif ou l'on porte un ballon ovale."},
        {"mot": "tennis", "indice": "Sport de raquette qui se joue avec une balle jaune sur un court."},
        {"mot": "hockey", "indice": "Sport rapide joue avec un baton et un palet ou une balle."},
        {"mot": "karate", "indice": "Art martial japonais base sur les coups de pied et de poing."},
        {"mot": "squash", "indice": "Sport de raquette joue dans une salle fermee avec quatre murs."},
        {"mot": "aviron", "indice": "Sport nautique ou l'on rame en equipe dans un bateau fin."},
        {"mot": "petanque", "indice": "Sport ou l'on lance des boules le plus pres possible d'un cochonnet."},
        {"mot": "billard", "indice": "Jeu ou l'on pousse des boules avec une queue sur une table."},
        {"mot": "bowling", "indice": "Sport ou l'on lance une boule pour faire tomber des quilles."},
        {"mot": "fitness", "indice": "Ensemble d'exercices physiques pratiques pour la forme."},
        {"mot": "trekking", "indice": "Longue randonnee pratiquee en terrain sauvage, souvent en montagne."},
        {"mot": "randonnee", "indice": "Longue marche pratiquee en pleine nature."},
        {"mot": "windsurf", "indice": "Sport nautique ou l'on tient une voile debout sur une planche."},
        {"mot": "kitesurf", "indice": "Sport nautique tracte par une aile de cerf-volant."},
        {"mot": "canyoning", "indice": "Sport qui consiste a descendre un cours d'eau encaisse en rappel et en saut."},
        {"mot": "parapente", "indice": "Sport aerien ou l'on vole suspendu a une grande voile souple."},
        {"mot": "alpinisme", "indice": "Sport qui consiste a gravir de hautes montagnes."},
        {"mot": "penalty", "indice": "Tir accorde apres une faute grave dans la surface au football."},
        {"mot": "arbitre", "indice": "Personne qui fait respecter les regles pendant un match."},
        {"mot": "champion", "indice": "Personne ou equipe qui remporte une competition."},
        {"mot": "medaille", "indice": "Recompense remise aux meilleurs d'une competition, souvent en or, argent ou bronze."},
        {"mot": "arbitrage", "indice": "Action de faire respecter les regles d'un sport."},
        {"mot": "cyclisme", "indice": "Sport pratique sur un velo, sur route ou en piste."},
        {"mot": "marathon", "indice": "Course a pied longue de 42,195 kilometres."},
        {"mot": "escrime", "indice": "Sport de combat a l'epee, au fleuret ou au sabre."},
        {"mot": "natation", "indice": "Sport pratique dans l'eau, sans planche ni bateau."},
        {"mot": "football", "indice": "Sport le plus populaire au monde, joue au pied avec un ballon rond."},
        {"mot": "baseball", "indice": "Sport americain ou l'on frappe une balle avec une batte."},
        {"mot": "softball", "indice": "Variante du baseball jouee avec une balle plus grosse et plus molle."},
        {"mot": "badminton", "indice": "Sport de raquette joue avec un volant plutot qu'une balle."},
        {"mot": "triathlon", "indice": "Epreuve qui enchaine natation, velo et course a pied."},
        {"mot": "plongeon", "indice": "Sport ou l'on saute d'un plongeoir en effectuant des figures."},
        {"mot": "escalade", "indice": "Sport qui consiste a grimper une paroi rocheuse ou artificielle."},
        {"mot": "patinage", "indice": "Sport pratique sur la glace avec des patins."},
        {"mot": "curling", "indice": "Sport ou l'on glisse des pierres sur la glace vers une cible."},
        {"mot": "snowboard", "indice": "Sport de glisse sur neige avec une seule planche."},
        {"mot": "biathlon", "indice": "Sport d'hiver qui combine ski de fond et tir a la carabine."},
        {"mot": "taekwondo", "indice": "Art martial coreen connu pour ses coups de pied spectaculaires."},
        {"mot": "speleologie", "indice": "Sport qui consiste a explorer des grottes souterraines."},
        {"mot": "deltaplane", "indice": "Aile volante rigide sur laquelle un pilote est suspendu."},
        {"mot": "orientation", "indice": "Sport ou l'on doit trouver des balises en pleine nature a l'aide d'une carte."},
        {"mot": "supporteur", "indice": "Personne qui encourage passionnement une equipe ou un athlete."},
        {"mot": "entrainement", "indice": "Ensemble des seances de preparation avant une competition."},
        {"mot": "competition", "indice": "Evenement ou plusieurs concurrents s'affrontent pour la victoire."},
        {"mot": "musculation", "indice": "Sport qui vise a developper la force et le volume musculaire."},
        {"mot": "athletisme", "indice": "Ensemble de disciplines comme la course, le saut et le lancer."},
        {"mot": "equitation", "indice": "Sport qui consiste a monter et diriger un cheval."},
        {"mot": "gymnastique", "indice": "Sport qui combine souplesse, force et acrobaties au sol ou aux agres."},
        {"mot": "halterophilie", "indice": "Sport de force qui consiste a soulever des barres chargees de poids."},
        {"mot": "skateboard", "indice": "Sport de glisse urbain pratique sur une planche a roulettes."},
        {"mot": "volleyball", "indice": "Sport collectif ou deux equipes se renvoient un ballon par-dessus un filet."},
        {"mot": "basketball", "indice": "Sport collectif ou il faut faire rentrer un ballon dans un panier."},
        {"mot": "parachutisme", "indice": "Sport extreme qui consiste a sauter d'un avion en chute libre."},
    ],
}

DIFFICULTES: dict[str, tuple[int, int]] = {
    "facile": (4, 6),
    "moyen": (7, 9),
    "difficile": (10, 99),
}

MULTIPLICATEUR_SCORE: dict[str, float] = {"facile": 1, "moyen": 1.5, "difficile": 2}

ERREURS_MAX = 6


def choisir_mot_et_indice(categorie: str, difficulte: str) -> tuple[str, str]:
    """Choisit un mot au hasard dans une categorie, filtre par la plage de longueur de la difficulte.

    Returns:
        Un tuple (mot, indice).
    """
    min_len, max_len = DIFFICULTES.get(difficulte, (0, 99))
    entrees_disponibles = MOTS.get(categorie, MOTS["informatique"])
    entrees_possibles = [e for e in entrees_disponibles if min_len <= len(e["mot"]) <= max_len]
    if not entrees_possibles:
        entrees_possibles = entrees_disponibles
    choisi = random.choice(entrees_possibles)
    return choisi["mot"], choisi["indice"]


def calculer_score(mot: str, erreurs: int, difficulte: str) -> int:
    """Calcule le score final selon la longueur du mot, les erreurs et la difficulte."""
    base = len(mot) * 10
    penalite = erreurs * 5
    score = (base - penalite) * MULTIPLICATEUR_SCORE.get(difficulte, 1)
    return max(0, round(score))


def calculer_points_contribution(lettres_correctes: int, difficulte: str) -> int:
    """Points bonus attribues a un joueur selon son nombre de lettres correctes trouvees.

    Utilise en mode Classique pour classer les joueurs par contribution individuelle,
    au lieu d'une simple victoire/defaite d'equipe.
    """
    return round(lettres_correctes * 10 * MULTIPLICATEUR_SCORE.get(difficulte, 1))